version: "3"
services:
  client:
    build: .

  hobby-swagger:
    image: lscr.io/linuxserver/swag
    container_name: hobby-swagger
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=whittakerxyz.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/ethan/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
    - 0.0.0.0:3007:443
    restart: unless-stopped
